name: iptv_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4 # or the latest version
  cupertino_icons: ^1.0.6
  lecle_yoyo_player: ^0.0.8
  google_fonts: ^6.2.1
  http: ^1.2.1
  flutter_cache_manager: ^3.3.2
  cached_network_image: ^3.3.1
  path_provider: ^2.1.3
  lottie: ^1.3.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  provider: ^6.1.2
  shared_preferences: ^2.0.6
  flex_color_scheme: ^7.3.1
  cast: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.jpeg"

flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/images/Movies/

  # Uncomment and update fonts section if you have custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
